javascripts:
  app:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery.masonry.min.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/jquery.oembed.min.js
    - public/javascripts/application.js
stylesheets:
  app:
    - public/stylesheets/scaffold.css
    - public/stylesheets/layout.css